### ISSUE TITLE
Panic when one attribut has invalid type

### ISSUE THREAD

**Issue by piclemx** [pulumi/pulumi-kafka#21]
```
Diagnostics:
  kafka:index:Topic (topicName):
    error: transport is closing
  pulumi:pulumi:Stack (stackname):
    [TRACE] [Sarama]2020/04/30 17:51:57 Initializing new client
    [TRACE] [Sarama]2020/04/30 17:51:57 client/metadata fetching metadata for all topics from broker broker1:9093
    [TRACE] [Sarama]2020/04/30 17:51:57 Connected to broker at broker2:9093 (unregistered)
    [TRACE] [Sarama]2020/04/30 17:51:59 client/brokers registered new broker #1005 at broker3:9093
    [TRACE] [Sarama]2020/04/30 17:51:59 client/brokers registered new broker #1003 at  (registered as #1008)
    panic: fatal: An assertion has failed
    goroutine 136 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.1-0.20200424001829-090f390d7b1a/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.1-0.20200424001829-090f390d7b1a/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInputs(0xc000d06ec0, 0x0, 0xc000cf05a0, 0x0, 0x0, 0xc000d034a0, 0xc000276150, 0xc000c90101, 0x16, 0x0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:104 +0x2369
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInput(0xc000d06ec0, 0xc000c9e618, 0x8, 0x0, 0x0, 0x2052540, 0xc000cf05a0, 0x0, 0x0, 0xc000d034a0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:489 +0xe9a
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInputs(0xc000d06ec0, 0x0, 0xc000cf0510, 0x0, 0x0, 0xc000d034a0, 0xc000276150, 0x101, 0xc000d03590, 0x0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:112 +0x21c
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInput(0xc000d06ec0, 0xc000c9e600, 0x4, 0x0, 0x0, 0x2052540, 0xc000cf0510, 0x0, 0x0, 0xc000d034a0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:489 +0xe9a
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInputs(0xc000d06ec0, 0x0, 0xc000cf0450, 0x0, 0x0, 0xc000d034a0, 0xc000276150, 0x101, 0x200, 0xe0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:112 +0x21c
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInput(0xc000d06ec0, 0xc000c9ef70, 0x8, 0x0, 0x0, 0x2052540, 0xc000cf0450, 0x0, 0x0, 0xc000d034a0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:489 +0xe9a
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInput(0xc000d06ec0, 0xc000c9e5a0, 0x5, 0x0, 0x0, 0x1e70d00, 0xc000d060e0, 0x0, 0x0, 0xc000d034a0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:434 +0x4d2
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInputs(0xc000d06ec0, 0x0, 0xc000cf0420, 0x0, 0x0, 0xc000d034a0, 0xc000276150, 0x1fa0101, 0x1e8ec00, 0x100000000000000, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:112 +0x21c
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInput(0xc000d06ec0, 0xc000c588c0, 0x11, 0x0, 0x0, 0x2052540, 0xc000cf0420, 0x0, 0x0, 0xc000d034a0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:489 +0xe9a
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInputs(0xc000d06ec0, 0x0, 0xc000cf03f0, 0x0, 0x0, 0xc000d034a0, 0xc000276150, 0xc000ce0101, 0xc000cecd38, 0x1ac550e, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:112 +0x21c
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInput(0xc000d06ec0, 0xc000c9ef66, 0x6, 0x0, 0x0, 0x2052540, 0xc000cf03f0, 0xc0002b3b80, 0x0, 0xc000d034a0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:489 +0xe9a
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInputs(0xc000d06ec0, 0xc000cf0390, 0xc000cf03c0, 0xc00057e750, 0xc00057e960, 0xc000d034a0, 0xc000276150, 0x2000001, 0x205b940, 0x0, ...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/schema.go:112 +0x21c
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Check(0xc0005a8480, 0x24c0820, 0xc000cf0300, 0xc000c9b3c0, 0xc0005a8480, 0x1f2a101, 0xc000c9b5c0)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.1.0/pkg/tfbridge/provider.go:488 +0x629
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler.func1(0x24c0820, 0xc000cf0300, 0x2065720, 0xc000c9b3c0, 0x20a02a0, 0x2ec19a0, 0x24c0820, 0xc000cf0300)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.1-0.20200424001829-090f390d7b1a/proto/go/provider.pb.go:1848 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x24c0820, 0xc000cd41e0, 0x2065720, 0xc000c9b3c0, 0xc000cd6360, 0xc000cd6380, 0x0, 0x0, 0x2499b80, 0xc0003e1220)
        /home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f9
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler(0x20c5380, 0xc0005a8480, 0x24c0820, 0xc000cd41e0, 0xc000ca8780, 0xc00000cb00, 0x24c0820, 0xc000cd41e0, 0xc000cd9200, 0x82d)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.1-0.20200424001829-090f390d7b1a/proto/go/provider.pb.go:1850 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000353040, 0x24d1520, 0xc0005a8a80, 0xc0004f3b00, 0xc00057ee10, 0x2e931f8, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082 +0x4fd
    google.golang.org/grpc.(*Server).handleStream(0xc000353040, 0x24d1520, 0xc0005a8a80, 0xc0004f3b00, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xd23
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004ef660, 0xc000353040, 0x24d1520, 0xc0005a8a80, 0xc0004f3b00)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1
```

`index.ts`
```
import { config } from './config';
import { Topic } from '@pulumi/kafka';

const topicName = `${config.productCode}.${config.environment}.audit`;
const topic = new Topic(topicName, {
  name: topicName,
  partitions: config.partitions,
  replicationFactor: config.replicationFactor,
  config: {
    'cleanup.policy': 'delete',
    'message.max.bytes': config.maxMessageSize.to('bytes'),
    'retention.ms': config.retentionTime.as('milliseconds'),
    'min.insync.replicas': config.replicationFactor - 1,
  },
});

export const output = { topic: topic.id };
```
`config.ts`
```
import * as pulumi from '@pulumi/pulumi';
import { Duration } from 'luxon';
import { unit, Unit } from 'mathjs';

const rawConfig = new pulumi.Config();

function requireEnv(key: string): string {
  const v = process.env[key];

  if (v === undefined) {
    throw new Error(`Missing required environment variable '${key}'`);
  }
  return v;
}

function requireDuration(key: string): Duration {
  const value = rawConfig.require(key);
  return Duration.fromISO(value);
}

function requireUnit(key: string): Unit {
  const value = rawConfig.require(key);
  return unit(value);
}

export const config = {
  partitions: rawConfig.requireNumber('partitions'),
  replicationFactor: rawConfig.requireNumber('replicationFactor'),
  retentionTime: requireDuration('retentionTime'),
  maxMessageSize: requireUnit('maxMessageSize'),
  productCode: rawConfig.require('product_code'),
  environment: rawConfig.require('environment'),
};

```

`Pulumi.yaml`
```
name: app
runtime: nodejs
description: 
config:
  # kafka:bootstrapServers: '["broker1:9092"]'
  kafka:tlsEnabled: "true"
  kafka:skipTlsVerify: "true"
  app:environment: env
  app:maxMessageSize: 10MB
  app:partitions: "1"
  app:replicationFactor: "2"
  app:retentionTime: 24h
```

**Comment by AaronFriel** [comment]
@piclemx If this issue still exists in the provider, please create a new issue with a repro.
